apiVersion: v1
kind: Service
metadata:
  name: svc-101
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
  selector:
    app: web